//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int CartID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> MaterialID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Image Image { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
        public virtual Material Material { get; set; }
    }
}
