//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionGroup
    {
        public int FunctionGroupID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Group Group { get; set; }
    }
}
